image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
services:
- docker:19.03.1-dind

before_script:
    - docker info
    - apk add --no-cache py2-pip python-dev libffi-dev openssl-dev gcc libc-dev make && pip install docker-compose

build:
    stage: build
    script:
        - docker info
        - docker-compose --version
        - docker-compose build