image: docker:edge-git
services:
- docker:dind

before_script:
    - apk add --no-cache py2-pip apk add python-dev libffi-dev openssl-dev gcc libc-dev make&& pip install docker-compose

build:
    stage: build
    script:
        - docker info
        - docker-compose --version