image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
services:
- docker:19.03.1-dind

before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_EXTERNAL_URL

build nginx:
    stage: build
    script:
        - docker pull $REGISTRY_EXTERNAL_URL/magento_nginx:latest
        - docker build docker/nginx/ --cache-from $REGISTRY_EXTERNAL_URL/magento_nginx:latest --tag $REGISTRY_EXTERNAL_URL/magento_nginx:$CI_COMMIT_SHA --tag $REGISTRY_EXTERNAL_URL/magento_nginx:latest 
        - docker push $REGISTRY_EXTERNAL_URL/magento_nginx:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_nginx:latest
        - docker pull $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest
        - docker build docker/php-fpm/ --cache-from $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest --tag $REGISTRY_EXTERNAL_URL/magento_php-fpm:$CI_COMMIT_SHA --tag $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest
        - docker push $REGISTRY_EXTERNAL_URL/magento_php-fpm:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest