image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
services:
- docker:19.03.1-dind

before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_EXTERNAL_URL

build nginx:
    stage: build
    script:
        - docker build docker/nginx/ --tag $REGISTRY_EXTERNAL_URL/magento_nginx:latest --tag $REGISTRY_EXTERNAL_URL:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_nginx:latest
        - docker push $REGISTRY_EXTERNAL_URL:$CI_COMMIT_SHA

build php-fpm:
    stage: build
    script:
        - docker build docker/php-fpm/ --tag $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest --tag $REGISTRY_EXTERNAL_URL:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest
        - docker push $REGISTRY_EXTERNAL_URL:$CI_COMMIT_SHA