image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
services:
- docker:19.03.1-dind

stages:
 - build
 - deploy

build:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_EXTERNAL_URL
        - docker pull $REGISTRY_EXTERNAL_URL/magento_nginx:latest || true
        - docker build docker/nginx/ --cache-from $REGISTRY_EXTERNAL_URL/magento_nginx:latest --tag $REGISTRY_EXTERNAL_URL/magento_nginx:$CI_COMMIT_SHA --tag $REGISTRY_EXTERNAL_URL/magento_nginx:latest 
        - docker push $REGISTRY_EXTERNAL_URL/magento_nginx:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_nginx:latest
        - docker pull $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest || true
        - docker build docker/php-fpm/ --cache-from $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest --tag $REGISTRY_EXTERNAL_URL/magento_php-fpm:$CI_COMMIT_SHA --tag $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest
        - docker push $REGISTRY_EXTERNAL_URL/magento_php-fpm:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento_php-fpm:latest
        
deploy:
  stage: deploy
  image: roffe/kubectl:latest
  script:
    - bash kubernetes/deploy-src/common.bash
    - kubectl --kubeconfig=./kubeconfig version
    - sed -e "s/{VERSION}/$CI_COMMIT_SHA/" kubernetes/patch-magento2-php-fpm.json
    - sed -e "s/{VERSION}/$CI_COMMIT_SHA/" kubernetes/patch-magento2-nginx.json
    - kubectl --kubeconfig=./kubeconfig patch statefulset $MAGENTO_STS --patch "$(cat kubernetes/patch-magento2-php-fpm.json)"
    - kubectl --kubeconfig=./kubeconfig patch statefulset $MAGENTO_STS --patch "$(cat kubernetes/patch-magento2-nginx.json)"
