image: docker:edge-git
services:
- docker:dind

before_script:
    - apk add --no-cache py2-pip && pip install docker-compose

build:
    stage: build
    script:
        - docker-compose build
run:
    stage: build
    script:
        - docker-compose up -d
