image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
services:
- docker:19.03.1-dind

before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_EXTERNAL_URL

build nginx:
    stage: build
    script:
        - docker build docker/nginx/ --tag $REGISTRY_EXTERNAL_URL/magento/ci-cd:$CI_COMMIT_SHA --tag $REGISTRY_EXTERNAL_URL/magento/ci-cd:latest 
        - docker push $REGISTRY_EXTERNAL_URL/magento/ci-cd:$CI_COMMIT_SHA
        - docker push $REGISTRY_EXTERNAL_URL/magento/ci-cd:latest