version: '3'
services:

  php-fpm:
    hostname: php-fpm.magento.loc     
    env_file:
      - .env
    build: ./php-fpm/.
    volumes: ['code-data:/var/www/html']
    links: 
     - mysql
     - redis
    depends_on:
     - mysql
     - redis

  nginx:
    env_file:
      - .env
    build: ./nginx/.
    volumes: ['code-data:/var/www/html']
    links:
      - php-fpm
    depends_on:
      - php-fpm
    ports:
     - "80:80"

  mysql:
    env_file:
      - .env
    image: mariadb:10.3
    ports:
     - "3306:3306"
    volumes: ['db-data:/var/lib/mysql']

  redis:
    image: redis:4.0.11

volumes:
  db-data: {}
  code-data: {}
      
